# Generated by Django 5.1.3 on 2024-12-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('cancellation_requested', 'Cancellation Requested'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
    ]
