# Generated by Django 5.1.3 on 2024-12-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_populate_order_status'),
        ('checkout', '0003_populate_order_status'),
    ]

    operations = [
    ]
